### ISSUE TITLE
Website crashes after installation, code 404

### ISSUE THREAD

**Issue by liorshap1** [realKfiros/stocks#1]
Hey there, I've encountered an error with your website and I don't know how to resolve it

**Comment by realKfiros** [comment]
@DeveloperCron can you reproduce and send the logs?

**Comment by liorshap1** [comment]
I couldn't re-produce but I could get the logs.
[CRASH LOG - 2024-08-01 12:34:56]

ERROR: Skibidi Toilet Overflow Exception at line 42
DETAILS: User attempted to perform a Fortnite dance emote in a non-emote zone. 

DEBUG INFO:
- Function: `performSkibidiToiletDance()`
- Error Code: FNT-1337
- Message: "Yo, stop trying to do the Skibidi Toilet here!"

STACK TRACE:
- at `performSkibidiToiletDance` (src/danceMoves.js:42)
- at `emoteHandler` (src/emoteHandler.js:28)
- at `main` (src/index.js:15)

ADDITIONAL INFO:
- User skin: "Fortnite Champa"
- Last emote used: "Floss Dance"
- Timestamp: 2024-08-01 12:34:56
- Location: Tilted Towers

SUGGESTIONS:
1. Please ensure that you are not attempting to Skibidi Toilet in restricted areas.
2. Consider switching to a more appropriate emote for this situation, such as the "Respectful Bow."
3. Check for updates to the EmoteHandler module to prevent future overflow exceptions.

USER NOTES:
- User reported the app was "acting sus" and "crashed mid Skibidi Toilet."
- User's feedback: "Bruh, this is cap. I was just tryna vibe!"

[end of log]

**Comment by realKfiros** [comment]
@DeveloperCron 
![image](https://github.com/user-attachments/assets/0a0df68d-7879-4a38-bf0e-e39b668f9f39)
